### ISSUE TITLE
Child Routes and Preloading

### ISSUE THREAD

**Issue by danielfliegauf** [MrFoxPro/solid-rollup-boilerplate#5]
Hello :) 

I tried to add child nodes to my app

```
const routes = [
  {
    name: 'landing',
    path: '/',
  },
  {
    name: 'home',
    path: '/home',
  },

  {
    name: 'groups',
    path: '/groups',
    children: [
      { name: 'view', path: '/:id<\\d+>' },
      { name: 'list', path: '/list' },
    ],
  },
  {
    name: 'settings',
    path: '/settings',
  },
] as const;

export const { Link, Router, Provider, router } = createSolidRouter(routes, {
  createRouter5: (routes) => {
    const router = createRouter(routes, {
      allowNotFound: true,
      autoCleanUp: true,
      defaultRoute: '/home',
    });
    router.usePlugin(browserPluginFactory({ useHash: false }));
    router.usePlugin(loggerPlugin);
    return router;
  },
});
```

but when I try to refresh the page with the url `localhost:3000/users/123`, I get following error msg and the page is not loaded :(

<img width="1030" alt="Screenshot 2020-12-08 at 13 40 28" src="https://user-images.githubusercontent.com/1799427/101485270-380b3d80-395b-11eb-9c72-546fda735a3a.png">

Routing via `router.router5.navigate('groups.view', { id: 12 });` works fine, so does refreshing the page with just the path `localhost:3000/groups` 🤔 

Does anyone have an idea, what this is about?

Help would be highly appreciated... since this is delaying my x-mas present ;( 
Thank you! :)

**Comment by 0x241F31** [comment]
Hi. I think I had similiar problem. Let me remind how had i fixed that.

**Comment by 0x241F31** [comment]
@danielfliegauf please try to update  `rollup-plugin-serve` to `1.1.0`,   `rollup-plugin-postcss` to `3.1.8`, `solid-js` and `babel-preset-solid`, `solid-typefu-router5` to latest versions. Also it is important to set `rollup-plugin-html2` url `git+https://github.com/MrFoxPro/rollup-plugin-html2.git` (I didn't update this boilerplate since I forked and rewoked this plugin).

**Comment by 0x241F31** [comment]
I've updated project, please try again

**Comment by 0x241F31** [comment]
![bolerplate_router_issue](https://user-images.githubusercontent.com/17229619/101510878-4594e780-399c-11eb-84d3-05d8d4f99fd6.gif)
I tested nested routes with reloading in browser, it works fine

**Comment by danielfliegauf** [comment]
Nice :) Thank you!

I also solved the bug by adding the following param to the rollup.config...
```onlinePath: '/',```
but I'll have a look at your fix asap

Thanks again for your fast response 👍

<img width="825" alt="Screenshot 2020-12-09 at 17 00 30" src="https://user-images.githubusercontent.com/1799427/101653956-3e271a00-3a40-11eb-9c8a-cfd0211f7c27.png">

**Comment by 0x241F31** [comment]
okay, merry christmas
